config/routes.rb
Citydogshare::Application.routes.draw do
  ## Route Route ##
  root :to => 'welcome#index'

  ## Session Routes ##
  get 'auth/:provider/callback', to: 'sessions#handle_auth', as: 'auth_success'
  get 'auth/failure', to: 'sessions#handle_failure', as: 'auth_failure'
  delete 'signout', to: 'sessions#destroy', as: 'signout'
  get 'create', to: 'sessions#create', as: 'create_session'
  get 'login', to: 'sessions#login', as: 'login'
  get 'signup', to: 'sessions#signup', as: 'signup'
  
  ## User Routes ##
  resources :users, only: [:show, :edit, :update, :destroy, :index]
  post 'users/:id/edit', to: 'users#edit'

  ## Dog Routes ##
  resources :dogs

  resources :events, :only => [:index, :new, :create, :edit, :update, :show, :destroy]

  resources :mixes, :only => [:index, :show] do
    collection do
      get :autocomplete
    end
  end

  resource :starred_dogs, only: [:create, :destroy]
  resources :users do
    member do
      get 'stars'
    end
  end
  #dog multiple pictures
  resources :pictures

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  get 'dashboard' => 'welcome#dashboard'
end

app/models/dog.rb
class Dog < ActiveRecord::Base
  include ActiveModel::ForbiddenAttributesProtection

  # attr_accessible :name, :image, :dob, :gender, :description, :motto, :fixed, :health, :comments, :contact, :availability, :mixes, :likes, :energy_level, :size, :personalities, :photo, :latitude, :longitude, :video

  scope :has_gender, lambda {|genders| filter_gender(genders)}
  scope :has_personalities, lambda {|personalities| filter_personality(personalities)}
  scope :has_likes, lambda {|likes| filter_like(likes)}
  scope :has_mix, lambda {|mix| filter_mix(mix)}
  scope :has_energy_level, lambda {|energy_levels| filter_energy_level(energy_levels)}
  scope :has_size, lambda {|sizes| filter_size(sizes)}
  scope :in_age_range, lambda {|age_query| filter_age(age_query)}

  belongs_to :user
  has_many :stars, :dependent => :destroy
  has_many :dog_mix_linkers
  has_many :dog_like_linkers
  has_many :dog_personality_linkers
  has_many :mixes, :through => :dog_mix_linkers
  has_many :likes, :through => :dog_like_linkers
  has_many :personalities, :through => :dog_personality_linkers
  belongs_to :energy_level
  belongs_to :size

  has_many :events, :dependent => :destroy

  geocoded_by :address


  validates :name, :presence => {:message => "Name can't be blank"}
  validates :mixes, :presence => {:message => "Mix can't be blank"}
  validate :validate_dob

  #paperclip avatar
  has_attached_file :photo, 
                    :styles => { :small    => '150x',
                                 :medium   => '300x' },
                    :default_url => "",
                    :storage => :s3,
                    :bucket => 'citydogshare',
                    :path => "/:class/:images/:id/:style/:basename.:extension"

  validates_attachment_size :photo, :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']

  #paperclip dog multiple pictures
  has_many :pictures, :dependent => :destroy

  after_validation :geocode

  ## Attribute Access Functions
  def validate_dob
    errors.add(:dob, "Dog's birthday can't be in the future.") if (!dob.nil? and dob > Date.today)
  end

  def age
    now = Time.now.utc.to_date
    now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
  end

  def age_caption
    y = age
    out = "< 1 year old" if y == 0
    out = "1 year old" if y == 1
    out = "#{y} years old" if y > 1
    out
  end

  def tags
    readable_personalities.join(", ") 
  end


  def energy_level
    EnergyLevel.find(self.energy_level_id).value
  end

  def size
    Size.find(self.size_id).value
  end

  def owner
    User.find(self.user_id)
  end

  def readable_mixes
    self.mixes.map {|m| m.value}
  end

  def readable_likes
    self.likes.map {|l| l.value}
  end

  def readable_personalities
    self.personalities.map {|p| p.value}
  end

  def address
    user = self.owner
    "#{user.zipcode}"
  end

  def youtube_id
    video.split(%r{v=|&})[1]

  end

  ## Attribute Possible Values Functions

  def self.genders
    ["Male", "Female"]
  end

  def self.age_ranges
    ["0-2 years", "2-4 years", "5-8 years", "9+ years"]
  end

  ## Filter Functions for Search Results (Dog Index Page)

  def self.filter_gender(genders)
    where("gender" => genders) unless genders.empty?
  end

  def self.filter_personality(personalities)
    joins(:personalities).where("personalities.value" => personalities) unless personalities.empty?
  end

  def self.filter_like(likes)
    joins(:likes).where("likes.value" => likes) unless likes.empty?
  end

  def self.filter_mix(mix)
    joins(:mixes).where("mixes.value" => mix) unless mix == "All Mixes"
  end

  def self.filter_energy_level(energy_levels)
    joins(:energy_level).where("energy_levels.value" => energy_levels) unless energy_levels.empty?
  end

  def self.filter_size(sizes)
    joins(:size).where("sizes.value" => sizes) unless sizes.empty?
  end
  
  def self.filter_age(age_query)
    where(age_query) unless age_query == ""
  end

  def self.convert_age_ranges_to_dob_query(age_ranges_indices)
    age_ranges = [[0, 2], [2, 4], [5, 8], [9, 30]]
    age_query = ""
    age_ranges_indices.each do |i|
        base = get_base(i.to_i, age_ranges)
        if i.to_i < age_ranges_indices.length - 1
          age_query += (base + " OR ")
        else
          age_query += base
        end
    end
    age_query
  end

  def self.get_base(i, ranges)
    first = (Time.now - ranges[i][1].years).strftime "%Y-%m-%d %H:%M:%S"
    second = (Time.now - ranges[i][0].years).strftime "%Y-%m-%d %H:%M:%S"
    base = %Q[("dogs"."dob" BETWEEN '#{first}' AND '#{second}')]
  end

  def self.filter_by(criteria)
    dogs = Dog.near(criteria[:zipcode], criteria[:radius])
              .has_mix(criteria[:mix])
              .has_size(criteria[:size])
              .has_likes(criteria[:like])
              .has_personalities(criteria[:personality])
              .has_gender(criteria[:gender])
              .has_energy_level(criteria[:energy_level])
              .in_age_range(convert_age_ranges_to_dob_query(criteria[:age]))
  end
  
  # Event Methods
  def future_events?
    # for all events, if at least one comes after yesterday, return true
    events.where("end_date > ?", 1.day.ago.midnight).pluck('end_date') != []
  end

  def future_events
    events.where("end_date > ?", 1.day.ago.midnight).order("start_date ASC")
  end

end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController

  require 'dog_form_filler'

  before_filter :current_user

  def index
    ip_zipcode = '94704'
    @form_filler = DogViewHelper.new(current_user, ip_zipcode, true)
    @form_filler.update_values(params, ip_zipcode, current_user)

    @dogs = Dog.filter_by @form_filler.values
    @no_dogs = @dogs.empty?

    @zipcodes = get_zipcode_from_dogs
    @counts = get_zipcode_counts.to_json
  end

  def get_ip_address_zipcode
    request.safe_location.postal_code
  end

  def new
    @form_filler = DogViewHelper.new(nil, nil, false)
    @action = :create
    @method = :post

    if params[:no_dog] == "true"
      @first_dog = true
      flash[:notice] = "Add your first dog"
      render 'new'
    end

    unless current_user.zipcode != nil and current_user.zipcode != "" 
      flash[:notice] = "Please update your zipcode to add a dog."
      redirect_to edit_user_path(current_user)
    end
  end


  def show
    id = params[:id]
    @dog = Dog.find(id)
    @parent = User.find(@dog.user_id)
    @pictures = @dog.pictures
  end

  def create
    @form_filler = DogViewHelper.new(nil, nil, false)
    @dog = Dog.new(@form_filler.attributes_list(dog_params))
    @dog.user_id = current_user.id
    if @dog.save      
      add_multiple_pictures(@dog)
      redirect_to user_path(current_user)
    else
      flash[:notice] = @dog.errors.messages
      render 'new'
    end
  end

  def edit 
    @form_filler = DogViewHelper.new(nil, nil, false)
    @dog = Dog.find(params[:id])
    @pictures = @dog.pictures
    @form_filler.dog_view_update(@dog)
    @action = :update
    @method = :put
  end

  def update
    @form_filler = DogViewHelper.new(nil, nil, false)
    @dog = Dog.find(params[:id])
    @pictures = @dog.pictures
    if @dog.update_attributes(@form_filler.attributes_list(dog_params))
      delete_checked_pictures        
      add_multiple_pictures(@dog)
      redirect_to dog_path(@dog.id)
    else
      flash[:notice] = @dog.errors.messages
      redirect_to edit_dog_path(@dog.id) 
    end
  end

  def destroy
    @dog = Dog.find(params[:id])
    @dog.photo.destroy
    @dog.delete
    redirect_to user_path(@current_user)
  end

  def get_zipcode_from_dogs
    @dogs.all.collect{|dog| dog.address}
  end

  def get_zipcode_counts
    wf = Hash.new(0)
    @zipcodes.each{|word| wf[word] += 1}
    wf
  end

  def dog_params
    params.require(:dog).permit(:name, :image, :dob, :gender, :description, 
    :motto, :fixed, :health, :comments, :contact, :availability, :mixes, 
    {:likes =>["dogs (all)", :cats, :men, :women, :children]}, :energy_level,
    :size, :photo, :latitude, :longitude, :video, "dob(1i)", "dob(2i)", "dob(3i)", 
    {:personalities =>[:anxious, :curious, :timid, :whatever, :friendly, :fetcher, :lover, "still a puppy"]})
  end

  def add_multiple_pictures(myDog)
    if params[:images]        
      params[:images].each { |image|
        myDog.pictures.create(image: image)
      }
    end
  end

  def delete_checked_pictures
    activated_ids = params[:activated].collect {|id| id.to_i} if params[:activated]
    seen_ids = params[:seen].collect {|id| id.to_i} if params[:seen]

    if activated_ids
      seen_ids.each do |id|          
        checked = activated_ids.include?(id)
        pic = Picture.find_by_id(id)
        pic.destroy if checked
      end
    end  
  end
end

app/views/dogs/edit.html.erb
<% if flash[:notice] %> 
  <div class="ui warning message"><i class="warning icon"></i>
    <% flash[:notice].each do |msg| %>
      <%= msg[1][0] %>
      <br>
    <% end %>
  </div>
<% end %>

<h2>Edit Your Dog's Profile</h2>

<%= render "edit_dog" %>

app/views/dogs/index.html.erb
<!-- <div class="large-12 columns"> -->
  <%= form_tag dogs_path, :method => :get do %>

  <div class="large-12 columns">
        <div class="large-6 columns">
        <div class="row">
            <div class="large-4 columns" style="text-align:center">
              Age:
              <br />
              <div class="tiny ui vertical buttons">
              <% Dog.age_ranges.each_with_index do |a, i| %>
              <div class="ui button">
              <%= check_box_tag "age[#{i}]", 1, @form_filler.values[:age].include?(i.to_s), :class => "check" %>
              <%= label(:age, i, a) %>
              </div>
              <% end %>
              </div>
            </div>

            <div class="large-3 columns" style="text-align:center">
              Gender:
              <br />
              <div class="tiny ui vertical buttons">
              <% Dog.genders.each do |gender| %>
              <div class="ui button">
              <%= check_box_tag "gender[#{gender}]", 1, @form_filler.values[:gender].include?(gender), :class => "check" %>
              <%= label(:gender, gender.tr(" ", "_"), gender) %>
              </div>
              <% end %>
              </div>
            </div>

            <div class="large-5 columns" style="text-align:center">
              Size:
              <br />
              <div class="tiny ui vertical buttons">
              <% Size.all_values.each do |s| %>
              <div class="ui button">
              <%= check_box_tag "size[#{s}]", 1, @form_filler.values[:size].include?(s), :class => "check" %>
              <%= label(:size, s.tr(" ", "_"), s) %>
              </div>
              <% end %>
              </div>
            </div>
        </div>
        <div class = "row">
            <br>
            

            <div style="text-align:center">
            <!--<%= label(:radius, "Dogs Within") %>-->
            Dogs within <%= text_field_tag(:radius, @form_filler.values[:radius], :size => 10  )%> miles of zipcode   
            <!--<%= label(:zipcode, "of") %>-->
            <%= text_field_tag(:zipcode, @form_filler.values[:zipcode], :size => 7) %>
      </div>
                Mix:
                <%= select_tag 'mix', options_for_select(["All Mixes"] + Mix.all_values, @form_filler.values[:mix]) %>
        </div>
    </div>
    <!-- </div> -->
    <div class="large-6 columns" style="text-align:center">
        <div class="large-4 columns">
          Personality:
          <br />
          <div class="mini ui vertical buttons">
          <% Personality.all_values.each do |p| %>
          <div class="ui button">
            <%= check_box_tag "personality[#{p}]", 1, @form_filler.values[:personality].include?(p), :class => "check" %>
            <%= label(:personality, p.tr(" ", "_"), p) %>
          </div>
          <% end %>
        </div>
    </div>
            <div class="large-3 columns" style="text-align:center">
          Energy:
          <br />
          <div class="mini ui vertical buttons">
          <% EnergyLevel.all_values.each do |e| %>
          <div class="ui button">
          <%= check_box_tag "energy_level[#{e}]", 1, @form_filler.values[:energy_level].include?(e), :class => "check" %>
          <%= label(:energy_level, e.tr(" ", "_"), e) %>
          </div>
          <% end %>
        </div>
        </div>

        <div class="large-5 columns" style="text-align:center">
          Likes:
          <br />
          <div class="mini ui vertical buttons">
          <% Like.all_values.each do |l| %>
          <div class="ui button">
          <%= check_box_tag "like[#{l}]", 1, @form_filler.values[:like].include?(l), :class => "check" %>
          <%= label(:like, l.tr(" ", "_"), l) %>
          </div>
          <% end %>
        </div>
        <br>
        <br>
      <div style="margin-left: -6em">
        <%= submit_tag 'Search Dogs', :id => 'dog_search_submit', :class => "ui primary button large transparent input" %>
      </div>
    </div>
    
    </div>
  <% end %>

<span id="zipcodes" data-zipcodes="<%= @zipcodes %>"/>
  <span id="counts" data-counts="<%= @counts %>"/>
  
  <div class="large-7 columns" >
    <br>
    <div class="ui segment" id="dog_search_results" style="padding: 0em">

    <% if @no_dogs %>
      <h1> No Dogs Found </h1>
    <% end %>
    <% @dogs.each do |dog| %>
    <% if dog.future_events? %>
    <div class="ui vertical segment" style="padding: 1em; border-style: solid; border-width: 1px; border-color: #5bbd72; border-radius: 3px" id = <%= dog.owner.zipcode %> >
    <div class="ui green bottom right attached right label" style="border-radius:0">Looking for a sitter!</div>

    <% else %>
    <div class="ui vertical segment" style="padding: 1em" id = <%= dog.owner.zipcode %> >
    <% end %>

      <div class="large-3 columns" style="padding: 0">
        <!-- <span class="image"> -->
          <div id="photo"><% if dog.photo.file? %>
          <%= image_tag dog.photo.url(:medium) %>
        <% else %>
          <%= image_tag "default_dog.jpg" %>
        <% end %></div>
        <!-- </span> -->
      </div>

      <div class="large-9 columns" style="padding-right: 0">
        <div class="content">
          <div class="ui medium header" style="margin-bottom: 0">
            <%= link_to dog.name, dog_path(dog) %>  
          <% if not current_user.nil? %>
          <span class="right floated stars">
            <%- unless current_user.starred_dogs.exists?(id: dog.id) -%>
              <%= link_to starred_dogs_path(dog_id: dog), method: :post, id: "star_#{dog.id}" do%>
              <i class="empty icon yellow large" style="margin-right: -0.3em"><%= dog.stars.count %></i><i class="empty star icon yellow large"></i>
              <%end%>
            <%- else -%>
              <%= link_to starred_dogs_path(dog_id: dog), method: :delete, id: "star_#{dog.id}" do%>
              <i class="icon yellow large" style="margin-right: -0.3em"><%= dog.stars.count %></i><i class="star icon yellow large"></i>
              <%end%>
            <%- end -%>
          </span>
          <%end%>
          </div>
          <div class="age">
            <b><%= dog.age_caption %></b>
          </div>
          <span class="right floated" style="margin-right: 5%">
            <%= dog.owner.zipcode %>
          </span>
          <div class="attributes">
            <b><%= dog.tags %></b>
          </div>
          <div class="description">
            <%= dog.motto %>
          </div>
        </div>
        <div class="extra content">
          <% unless dog.availability == "" %>
          <i class="wait icon"></i>
          <%= dog.availability %>
          <% end %>
        </div>
        <% if dog.future_events? %>
        <b>Next event:</b> <%= dog.future_events.first.start_date.strftime("%m/%d/%Y") %>
        <% end %>
      </div>

    </div>
    <% end %>
    </div>
  </div>

  <div class="large-5 columns" id="map">
        <br>
    <div class ="ui sticky">
    <div id="map-canvas">
      <!-- <img src="http://www.digicution.com/wp-content/uploads/2012/06/HTML5-Repsonsive-Google-Maps-Tutorial-1.png" style="height:100%; width:100%"> -->
    </div></div>
  </div>
</div>

<script type="text/javascript"
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCvpxxyVWimCzY6WLJTY8iYGUUkVy6q7bA">
</script>
<script>
$(document).ready(function(){
  $('.ui.sticky')
  .sticky({
    offset: 50,
    context: '#dog_search_results'
  });

  $('select.dropdown').dropdown(); 

  var geocoder;
  var map;
  var query = $('#zipcodes').data('zipcodes');
  var counts = $('#counts').data('counts');
  //var query = ['2523 Ridge Road, Berkeley, CA', 'Berkeley'];
  function initialize() {
    geocoder = new google.maps.Geocoder();
    var mapOptions = {
      zoom: 8, 
      streetViewControl: false,
      zoomControl: true
    }
    map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
    var bounds = new google.maps.LatLngBounds();
    codeAddress(counts, bounds);
    
  }

//  Fit these bounds to the map

  function codeAddress(counts, bounds) {
    var address = query;
    var visited = [];
    
    for (i = 0; i < address.length; i++) {
        

        if ($.inArray(address[i], visited) == -1) {
            visited.push(address[i]);

        geocoder.geocode( { 'address': address[i]}, function(results, status) {
        if (status == google.maps.GeocoderStatus.OK) {
          //map.setCenter(results[0].geometry.location);
          var current = results[0].address_components[0].long_name;
          
          var marker = new google.maps.Marker({
              map: map,
              icon: "http://chart.apis.google.com/chart?chst=d_map_pin_letter&chld="+counts[current]+"%7CFE6256%7C000000",
              url: '#' + current,
              position: results[0].geometry.location
          });
          google.maps.event.addListener(marker, 'click', function() {
            $('body').animate({scrollTop: $(marker.url).offset().top - 50}, 'slow');
          });
          bounds.extend(marker.getPosition());
          map.fitBounds(bounds);

        } 
    });
    }
}

  }

  google.maps.event.addDomListener(window, 'load', initialize);
});
</script>

app/views/dogs/new.html.erb
<% if flash[:notice] %>
  <div class="ui warning message"><i class="warning icon"></i>
  	<% if @first_dog %>
    	<%= flash[:notice] %>
    <% else %>
   		<% flash[:notice].each do |msg| %>
    		<%= msg[1][0] %>
    		<br />
    	<% end %>
    <% end %>
  </div>
<% end %>

<h2>Create Your Dog's Profile</h2>

<%= render 'dog_form' %>


<!--<script>
//   $(document).ready(function(){
//     $.each($(':checked'), function( index, value ) {
//       $(value).parent().addClass('active');
//     });
    
//     $('.ui.button').click(function(){
//       $(this).toggleClass('active');
//       var $this_checkbox = $($(this).children());
//       if ($this_checkbox.is(':checked')){
//         $this_checkbox.prop('checked', false);
//       } else {
//         $this_checkbox.prop('checked', true);
//       }
//     });
    
//     $('.check').click(function(){
//       $(this).parent().toggleClass('active');
//     });
//   });
  </script>-->

app/views/dogs/show.html.erb
<script src="<%= javascript_path('galleria-1.4.2.js') %>"></script>
<% if flash[:notice] %>
         <div class="notice"><%= flash[:notice] %></div>
<% end %>

<div class="large-12 columns">
  <br />
  <!-- THIS IS DOG INFO -->
  <div class="large-6 columns" id ="dog_info_stats">
    <div class="ui blue inverted top attached segment" style="overflow:hidden">
      <div class="ui blue top right attached label">
        

        <% if not current_user.nil? %>
          <div class="stars">
          <%- unless current_user.starred_dogs.exists?(id: @dog.id) -%>
          <%= link_to starred_dogs_path(dog_id: @dog), method: :post, id: "star_#{@dog.id}" do%>
          <i class="empty icon white large"><%= @dog.stars.count %></i><i class="empty star icon white large"></i>
          <%end%>
          <% else %>
          <%= link_to starred_dogs_path(dog_id: @dog), method: :delete, id: "star_#{@dog.id}"  do%>
          <i class="icon white large"><%= @dog.stars.count %></i><i class="star icon white large"></i>
          <%end%>
          <% end %>
          </div>
        <%end%>


      </div>
      <div id="name">
        <% if @dog.photo.file? %> 
        <h1><%= image_tag @dog.photo.url(:small), :class => "ui avatar image" %> <%= @dog.name %></h1>
        <% else %>
        <h1><%= image_tag "default_dog.jpg", :class => "ui avatar image" %> <%= @dog.name %></h1>
        <% end %>
      </div>
    </div>
    <div class="ui bottom attached segment">
      <% if not @dog.motto.nil? and not @dog.motto == "" %>
        <h3 class = "ui ribbon label"> <%= @dog.motto %> </h3>
        <br /><br />
      <% end %>
      <p>
        <em><%= @dog.description %></em> 
      </p>
      <p>
        <strong>Mix:</strong> <%= @dog.readable_mixes.join(', ') %> <br />
        <strong>Stats:</strong> <%= @dog.gender %>, <%= @dog.age %> years old, <%= @dog.size %>,
        <% if @dog.fixed %> fixed<% else %> not fixed<% end %> <br />
        <strong>Energy Level:</strong> <%= @dog.energy_level %>
        <% if not @dog.personalities.empty? %><br /><strong>Personality:</strong> <%= @dog.readable_personalities.join(', ') %><% end %>
      </p>
      <% if not @dog.likes.empty? %>
      <p>
        <i class="thumbs outline up icon"></i> <%= @dog.readable_likes.join(', ') %>
      </p>
      <% end %>
      <% if not @dog.health.nil? and not @dog.health == ""  %>
      <p>
        <i class="first aid icon"></i> <%= @dog.health %>
      </p>
      <% end %>
      <% if not @dog.availability.nil? and not @dog.availability == ""  %>
      <p>
        <i class="wait icon"></i> <%= @dog.availability %>
      </p>
      <% end %>
      <br />
      <div class="ui bottom right attached label">My parent is <span style="color:#3b83c0"><%= link_to @parent.first_name, user_path(@parent.id) %></span> <%= image_tag @parent.image, :class => "ui avatar image" %></div>
    </div>

<!-- THIS IS THE EVENTS LISTING -->
      <div class="ui blue inverted top attached segment">
        <strong><%= @dog.name %>'s Events:</strong>
      </div>
      <div class="ui bottom attached segment">
        <% if @dog.future_events? == false || @dog.events.count == 0 %>
          <h1> No Upcoming Events </h1>
        <% end %>
        <% @dog.future_events.each do |event| %>
        <div class="ui vertical segment">
          <div class="large-9 columns">
            <strong>  
              <% if event.start_date == event.end_date %>
                <%= event.start_date.strftime('%v') %>
              <% else %>
                <%= event.start_date.strftime('%v') %> to <%= event.end_date.strftime('%v') %>
              <% end %>
            </strong>
          </div>
          <div class="large-3 columns">
            <% if not @current_user.nil? and @current_user.id == @dog.user_id %>
              <%= link_to "Edit", edit_event_path(event.id) %></p>
            <% end %>
          </div>
            <div class="large-12 columns content">
              <strong>Time:</strong> <%= event.time_of_day.join(", ") %></br>
              <strong>Where:</strong> <%= event.my_location %></br>
              <% if event.description != "" %>
                <strong>Description:</strong> <%= event.description %>
              <% end %>
            </div>
        </div>
        <% end %>
      </div>
    <br />
  </div>

<!-- THIS IS DOG PHOTOS AND VIDEO -->
  <!-- <div class="ui rail"> -->
    
    <div class="large-6 columns">
      <div class="ui sticky">
        <div class="galleria">
          <% unless @pictures.empty? %>
            <% @pictures.each do |pic| %>
              <%= image_tag pic.image.url %>               
            <% end %>
          <% end %>
        </div>
        <script>
          Galleria.loadTheme("<%= javascript_path('galleria.classic.js') %>");
          Galleria.run('.galleria' , { height: 0.6,  } );
        </script>
        <p> </p>

        <% if not @dog.video.nil? and not @dog.video == "" %>
        <div class="ui video" data-source="youtube" data-id="<%= @dog.youtube_id %>" ></div>
        <% end %>
      </div>
    </div>
    <p>
  <% if not @current_user.nil? and @dog.user_id == @current_user.id %>
    <div class ="float right">
     <%= button_to "Delete", dog_path(@dog.id), :id => "delete_dog_button", :class => "ui button red transparent input", :method => :delete %>
  </div>
  <div class = "float right">
      <%= button_to "Edit", edit_dog_path(@dog.id), :id => "edit_dog_button", :class => "ui primary button", :method => :get %>

  </div>

  <% end %>

</p>
  <!-- </div> -->
</div>






<script>
$(document).ready(function(){
  $('.ui.video').video();

  $('.ui.sticky')
  .sticky({
    offset: 50,
    context: '#dog_info_stats'
  });
});
</script>