config/routes.rb
Citydogshare::Application.routes.draw do
  ## Route Route ##
  root :to => 'welcome#index'

  ## Session Routes ##
  get 'auth/:provider/callback', to: 'sessions#handle_auth', as: 'auth_success'
  get 'auth/failure', to: 'sessions#handle_failure', as: 'auth_failure'
  delete 'signout', to: 'sessions#destroy', as: 'signout'
  get 'create', to: 'sessions#create', as: 'create_session'
  get 'login', to: 'sessions#login', as: 'login'
  get 'signup', to: 'sessions#signup', as: 'signup'
  
  ## User Routes ##
  resources :users, only: [:show, :edit, :update, :destroy, :index]
  post 'users/:id/edit', to: 'users#edit'

  ## Dog Routes ##
  resources :dogs

  resources :events, :only => [:index, :new, :create, :edit, :update, :show, :destroy]

  resources :mixes, :only => [:index, :show] do
    collection do
      get :autocomplete
    end
  end

  resource :starred_dogs, only: [:create, :destroy]
  resources :users do
    member do
      get 'stars'
    end
  end
  #dog multiple pictures
  resources :pictures

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  get 'dashboard' => 'welcome#dashboard'
end

app/models/user.rb
class User < ActiveRecord::Base 
  include ActiveModel::ForbiddenAttributesProtection
  
  # attr_accessor :first_name, :last_name, :location, :gender, :image, :status, :phone_number, :email, :availability, :description, :address, :zipcode, :city, :country
  validates :phone_number, format: { with: /\(\d{3}\)(\ ?)\d{3}-\d{4}/, message: "Bad format for phone number." }, :allow_blank => true
  validates :zipcode, format: { with: /\d{5}/, message: "Bad format for zipcode."}, :allow_blank => true
  has_many :dogs, :dependent => :destroy
  has_many :events, :through => :dogs

  has_many :stars, :dependent => :destroy
  has_many :starred_dogs, through: :stars, :source => :dog

  def update_credentials(credentials)
    self.oauth_token = credentials[:token]
    self.oauth_expires_at = Time.at(credentials[:expires_at].to_i)
    self.save 
  end

  def facebook_info_update(auth)
    self.uid = auth[:uid]
    if(auth[:extra][:raw_info] != nil)
      self.gender = auth[:extra][:raw_info][:gender]
    end
    self.first_name = auth[:info][:first_name]
    self.last_name = auth[:info][:last_name]
    self.image = auth[:info][:image][0..-7] + "large"
    self.location = auth[:info][:location]
    self.email = auth[:info][:email]
    self.save
  end

  def full_name
    return "#{self.first_name} #{self.last_name}"
  end

  def future_events?
    # for all events, if at least one comes after yesterday, return true
    events.where("end_date > ?", 1.day.ago.midnight).pluck('end_date') != []
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :current_user

  def show
    if User.exists?(params[:id]) == false
      flash[:notice] = "The user you entered does not exist."
      redirect_to @current_user
    else
      id = params[:id]
      @own_profile = false
      @user = User.find(id)
      if @user == @current_user
        @own_profile = true
      end
      render 'show'
    end
  end

  def edit
    if User.exists?(params[:id]) == false || User.find(params[:id]) != @current_user
      flash[:notice] = "You may only edit your own profile."
      redirect_to @current_user
    elsif params[:user] != nil and @current_user.update_attributes(user_params)
      @current_user.dogs.each do |dog|
        dog.geocode
        dog.save
      end
      flash[:notice] = "Profile successfully updated."
      redirect_to @current_user
    else
      render 'edit'
    end
  end

  def destroy
    @current_user.destroy
    # Don't like this... I wanted to redirect to sessions#destroy, but redirect_to doesn't do DELETE methods
    session[:user_id] = nil
    redirect_to root_path()
  end

  def stars
    if !current_user.nil? and current_user.id != params[:id].to_i
      redirect_to(stars_user_path(current_user)) and return
    end
    @dogs = User.find_by_id(params[:id]).starred_dogs
  end

  private
  def user_params
    if params[:user]
      params.require(:user).permit(:first_name, :last_name, :location, :gender, :image, :status, :phone_number, :email, :availability, :description, :address, :zipcode, :city, :country)
    end
  end
end

app/views/users/edit.html.erb
<% if current_user.errors.any? %>
  <div class="ui warning message"><i class="warning icon"></i>
    <% current_user.errors.messages.each do |msg| %>
      <%= msg[1][0] %>
      <br>
    <% end %>
  </div>
<% end %>
<% if flash[:notice] %>
  <div class="ui warning message"><i class="warning icon"></i><%= flash[:notice] %></div>
<% end %>
<h2>Edit Your Profile</h2>
<div class="float right"><%= button_to "Delete User", user_path(@current_user.id), :id => "delete_user_button", :class => "ui button red transparent input", :method => :delete %></div>
    <div class="field">
      <div id="picture" class="ui medium centered image"><img src=<%="#{current_user.image}"%>></div>
    </div>

 <div class="field">
      <label>First Name</label>
      <div id="first_name" class="required ui fluid segment"><%= "#{current_user.first_name}"%></div>
    </div>

    <div class="field">
      <label>Last Name</label>
      <div id="last_name" class="required ui fluid segment"><%= "#{current_user.last_name}"%></div>
    </div>

    <div class="field">
      <label>Email</label>
      <div id="email" class="required ui fluid segment"><%= "#{current_user.email}"%></div>
    </div>
<%= form_tag(controller: "users", action: "edit", method: "post") do %>
<div class="ui form">  
  <div class="field"><label>Address</label>
  <% if current_user.address != nil && current_user.address != ""%>
  <%= text_field(:user, :address, :value => current_user.address) %>
  <%else%>
  <%= text_field(:user, :address, :placeholder => 'Street number and street') %>
  <%end %>
  </div>


  <div class="field"><label>City</label>
  <% if current_user.city != nil && current_user.city != ""%>
  <%= text_field(:user, :city, :value => current_user.city) %>
  <%else%>
  <%= text_field(:user, :city, :placeholder => 'City') %>
  <%end %>
  </div>
Zipcode will be required to share your dog. Your information will not be shown to other users.
  <div class="field"><label>Zipcode</label>
  <% if current_user.zipcode != nil && current_user.zipcode != ""%>
  <%= text_field(:user, :zipcode, :value => current_user.zipcode) %>
  <%else%>
  <%= text_field(:user, :zipcode, :placeholder => 'xxxxx') %>
  <%end %>
  </div>

  <div class="field"><label>Country</label>
  <% if current_user.country != nil && current_user.country != ""%>
  <%= text_field(:user, :country, :value => current_user.country) %>
  <%else%>
  <%= text_field(:user, :country, :placeholder => 'Country') %>
  <%end %>
  </div>

  <div class="field"><label>Phone Number</label>
  <% if current_user.phone_number != nil && current_user.phone_number != ""%>
  <%= telephone_field(:user, :phone_number, :value => current_user.phone_number) %>
  <%else%>
  <%= telephone_field(:user, :phone_number, :placeholder => '(xxx)xxx-xxxx') %>
  <% end %>
  </div>

  <div class="field"><label>Status</label>
  <% if current_user.status != nil %>
  <%= select(:user, :status, ["Looking", "Sharing"], :selected => current_user.status) %>
  <% else %>
  <%= select(:user, :status, ["Looking", "Sharing"])%>
  <%end%>
  </div>


  <div class="field"><label>Description</label>
  <% if current_user.description != nil && current_user.description != ""%>
    <%= text_field(:user,:description, :value => current_user.description) %>
  <% else %>
    <%= text_field(:user,:description, :placeholder => 'Tell City Dog Share more about yourself.') %>
  <%end%>
  </div>

  <div class="field"><label>Availability</label>
  <% if current_user.availability != nil && current_user.availability != ""%>
   <%= text_field(:user,:availability, :value => current_user.availability)%>
 <%else%>
   <%= text_field(:user,:availability, :placeholder => 'What is your availability for dog sitting, if applicable?')%>
 <%end%>
 </div>

<div class="ui primary button transparent input"><input id='update_user_button' type="submit" value="Save Changes" name="update_user_button" class='btn info'  style="text-align:center"/></div>

<% end %>

<%= button_to "Cancel Changes", user_path(@current_user.id), :id => "cancel_user_button", :class => "ui button transparent input", :method => :get %>


</div>

app/views/users/show.html.erb
<% if flash[:notice] %>
<div class="ui warning message"><i class="warning icon"></i><%= flash[:notice] %></div>
<% end %>


<div class="large-12 columns">
  <br />
  <div class="large-7 columns" id ="user_info">
    <div class="ui blue inverted top attached segment" style="overflow:hidden">
      <div id="name">
        <h1><%= image_tag @user.image, :class => "ui middle aligned small image", :id => "ui-segment" %>&nbsp; <%= @user.full_name %></h1>
      </div>
    </div>

<div class="ui bottom attached segment">



  <% if not @user.description.nil? and not @user.description == ""  %>
  <div id="user_description">
    <div id="description">
      <p>
        <em><%= @user.description %></em>
      </p>
    </div>
  </div>
  <%end%>


<br />

  <div id="gender"><strong>Gender:</strong>&nbsp;&nbsp;<%= @user.gender %></div>

<% if current_user %>
  <% if @user.address != nil && @user.address != ""%>
  <div id="location"><strong>Location:</strong>&nbsp;&nbsp;<%= "#{@user.address}, #{@user.city}, #{@user.zipcode}, #{@user.country}" %></div>
  <%end%>
<%else%>
  <% if @user.address != nil && @user.address != ""%>
  <div id="location"><strong>Location:</strong>&nbsp;&nbsp;You must <%= link_to "log in", "/auth/facebook/?type=login", id: 'log_in' %> to view!</div>
  <%end%>
<%end%>

  <% if not @user.zipcode.nil? and not @user.zipcode == ""  %>
  <div id="zipcode"><strong>Zipcode:</strong>&nbsp;&nbsp;<%= @user.zipcode %></div>
  <%end%>

  <div id="status"><strong>Status:</strong>&nbsp;&nbsp;<%= @user.status %></div>

<br />

  <% if current_user %>
    <p id="email">
      <i class="mail icon"></i> <%= @user.email %>
    </p>
  <!-- <div id="email"><strong>Email:</strong>&nbsp;&nbsp;<%= @user.email %></div> -->

  <% if not @user.phone_number.nil? and not @user.phone_number == ""  %>
    <p id="phone_number">
      <i class="call icon"></i> <%= @user.phone_number %>
    </p>
  <!-- <div id="phone_number"><strong>Phone Number:</strong>&nbsp;&nbsp;<%= @user.phone_number %></div> -->
  <%end%>

  <%else%>

  <p id="email"><i class="mail icon"></i> You must <%= link_to "log in", "/auth/facebook/?type=login", id: 'log_in' %> to view!</p>

  <% if not @user.phone_number.nil? and not @user.phone_number == ""  %>
  <p id="phone_number"><i class="call icon"></i> You must <%= link_to "log in", "/auth/facebook/?type=login", id: 'log_in' %> to view!</p>
  <%end%>

  <%end%>

  <% if not @user.availability.nil? and not @user.availability == ""  %>
    <p id="availability">
      <i class="wait icon"></i> <%= @user.availability %>
    </p>
  <%end%>

</div></div>

<div class="large-5 columns">    
   <div class="ui blue inverted top attached segment" style="overflow:hidden">
    <strong><%= @user.first_name %>'s Dogs:
   </strong>
  </div>

  <div class="ui bottom attached segment" id="dog-name-link">
  <!--<% if @no_dogs %>
    <h1> No Dogs Found </h1>
  <% end %>-->
  <% @user.dogs.each do |dog| %>
  <div class="ui vertical segment">

    <div class="large-4 columns">
      <span class="image">

        <% if dog.photo.file? %>
          <%= image_tag dog.photo.url(:small) %>
        <% else %>
          <%= image_tag "default_dog.jpg" %>
        <% end %>
      </span>
    </div>

    <div class="large-8 columns">
      <div class="content">
        <div class="ui medium header">
          <%= link_to dog.name, dog_path(dog.id), :method => :get %>
        </div>
        <div class="description">
          <%= dog.motto %>
        </div>
      </div>

    </div>

    <div>
                  <br /> <br />
    </div>
</div>
  <% end %>


  </div>
  <% if @own_profile %>
        <div class="float right">
        <%= button_to "Add Dog", new_dog_path(), :id => "add_dog_button", :class => "ui primary button", :method => :get %>
 

  </div>
  <% end %>
  <% if @own_profile %>
        <div class="float right">
        
        <%= button_to "Edit Profile", edit_user_path(@user.id), :id => "edit_user_button", :class => "ui primary button", :method => :get %>
      </div>
      <% end %>
<br />

</div>

</div>

</div>

app/views/users/stars.html.erb
<h2>Starred Dogs</h2>
<% if not @dogs.nil? %>
    <% @dogs.each do |dog| %>
    <% if dog.future_events? %>
    <div class="ui vertical segment" style="padding: 1em; border-style: solid; border-width: 1px; border-color: #5bbd72; border-radius: 3px" id = <%= dog.owner.zipcode %> >
    <div class="ui green bottom right attached right label" style="border-radius:0">Looking for a sitter!</div>

    <% else %>
    <div class="ui vertical segment" style="padding: 1em" id = <%= dog.owner.zipcode %> >
    <% end %>

      <div class="large-3 columns" style="padding: 0">
        <!-- <span class="image"> -->
                    <div id="photo"><% if dog.photo.file? %>
          <%= image_tag dog.photo.url(:medium) %>
        <% else %>
          <%= image_tag "default_dog.jpg" %>
        <% end %></div>
        <!-- </span> -->
      </div>

      <div class="large-9 columns" style="padding-right: 0">
        <div class="content">
          <div class="ui medium header" style="margin-bottom: 0">
            <%= link_to dog.name, dog_path(dog) %>  
          <% if not current_user.nil? %>
          <span class="right floated stars">
            <%- unless current_user.starred_dogs.exists?(id: dog.id) -%>
              <%= link_to starred_dogs_path(dog_id: dog), method: :post, id: "star_#{dog.id}" do%>
              <i class="empty icon yellow large" style="margin-right: -0.3em"><%= dog.stars.count %></i><i class="empty star icon yellow large"></i>
              <%end%>
            <%- else -%>
              <%= link_to starred_dogs_path(dog_id: dog), method: :delete, id: "star_#{dog.id}" do%>
              <i class="icon yellow large" style="margin-right: -0.3em"><%= dog.stars.count %></i><i class="star icon yellow large"></i>
              <%end%>
            <%- end -%>
          </span>
          <%end%>
          </div>
          <div class="age">
            <b><%= dog.age_caption %></b>
          </div>
          <span class="right floated" style="margin-right: 5%">
            <%= dog.owner.zipcode %>
          </span>
          <div class="attributes">
            <b><%= dog.tags %></b>
          </div>
          <div class="description">
            <%= dog.motto %>
          </div>
        </div>
        <div class="extra content">
          <% unless dog.availability == "" %>
          <i class="wait icon"></i>
          <%= dog.availability %>
          <% end %>
        </div>
        <% if dog.future_events? %>
        <b>Next event:</b> <%= dog.future_events.first.start_date.strftime("%m/%d/%Y") %>
        <% end %>
      </div>

    </div>
    <% end %>
<% else %>
  No starred dogs.
<%end%>