config/routes.rb
Citydogshare::Application.routes.draw do
  ## Route Route ##
  root :to => 'welcome#index'

  ## Session Routes ##
  get 'auth/:provider/callback', to: 'sessions#handle_auth', as: 'auth_success'
  get 'auth/failure', to: 'sessions#handle_failure', as: 'auth_failure'
  delete 'signout', to: 'sessions#destroy', as: 'signout'
  get 'create', to: 'sessions#create', as: 'create_session'
  get 'login', to: 'sessions#login', as: 'login'
  get 'signup', to: 'sessions#signup', as: 'signup'
  
  ## User Routes ##
  resources :users, only: [:show, :edit, :update, :destroy, :index]
  post 'users/:id/edit', to: 'users#edit'

  ## Dog Routes ##
  resources :dogs

  resources :events, :only => [:index, :new, :create, :edit, :update, :show, :destroy]

  resources :mixes, :only => [:index, :show] do
    collection do
      get :autocomplete
    end
  end

  resource :starred_dogs, only: [:create, :destroy]
  resources :users do
    member do
      get 'stars'
    end
  end
  #dog multiple pictures
  resources :pictures

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  get 'dashboard' => 'welcome#dashboard'
end

app/models/event.rb
class Event < ActiveRecord::Base
  # attr_accessible :start_date, :end_date, :time_of_day, :my_location, :dog, :description
  belongs_to :dog

  validates :start_date, :presence => {:message => "Please enter a valid start date"}
  validates :end_date, :presence => {:message => "Please enter a valid end date"}
  validates :time_of_day, :presence => {:message => "Please enter a time of day"}
  validates :dog, :presence => {:message => "Please select the dog you want to share"}

  serialize :time_of_day

  def color
    @num = dog_id % 10
    @colours = Array['blue','orange','green','yellow','brown','pink','purple','gray','cyan','magenta']
    if @num.between?(0,9) then @colours[@num] else 'black' end
  end

  def text_color
    if color == 'yellow' || color == 'pink' || color == 'orange' || color == 'cyan' || color == 'magenta'
      'black'
    else
      'white'
    end
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  require 'event_form_filler'

  before_filter :current_user

  def index
    @events = []
    @dogs = current_user.dogs
    @dogs.each do |dog|
      (@events << dog.events).flatten!

    end
  end

  def show
    id = params[:id]
    @event = Event.find(id)
    redirect_to dog_path(@event.dog_id)
  end

  def new
    @form_filler = EventViewHelper.new(current_user)
    @action = :create
    @method = :post

    unless @form_filler.all_dogs != []
      flash[:notice] = "Please create a dog to share"
      redirect_to user_path(current_user.id)
    end
  end


  def create
    @form_filler = EventViewHelper.new(current_user)
    @event_attr = @form_filler.event_info(params)
    @dogs = @form_filler.dogs
    set_flash

    if flash[:notice]
      render 'new'
    else
      redirect_to events_path
    end
  end


  def edit
    @event = Event.find(params[:id])
    @dog = Dog.find(@event.dog_id)
    @form_filler = EventViewHelper.new(current_user)
    @form_filler.event_view_update(@event)
    @action = :update
    @method = :put
  end



  def update
    @event = Event.find(params[:id])
    @dog = Dog.find(@event.dog_id)    

    @form_filler = EventViewHelper.new(current_user)
    @event_attr = @form_filler.event_info(params)
    @event_attr[:dog] = @dog
    if @event.update_attributes(@event_attr)
      redirect_to events_path
    else
      flash[:notice] = @event.errors.messages
      redirect_to edit_event_path(params[:id])
    end
  end


  def destroy
    @event = Event.find(params[:id])
    @event.delete
    flash[:notice] = "Your event has been deleted."
    redirect_to events_path
  end


  def set_flash
    if @dogs.empty?
      flash[:notice] = {:name => ["Please select a dog to share"]}
    elsif not create_events
      flash[:notice] = @event.errors.messages
    end
  end


  def create_events
    @dogs.each do |dog|
      @event_attr[:dog] = current_user.dogs.find_by_name(dog)
      @event = Event.new(@event_attr)
      if not @event.valid?
        return false
      else
        @event.save
      end
    end
  end


end

app/views/events/_event_form.html.erb
<!-- <link rel="stylesheet" type="text/css" href="../app/assets/stylesheet/jquery.datetimepicker.css"/ > -->
<!-- <script src="../app/assets/javascript/jquery.datetimepicker.js"></script> -->
<script>
  jQuery(function(){
   jQuery('#date_timepicker_start').datetimepicker({
    format:'Y/m/d',
    onShow:function( ct ){
     this.setOptions({
      minDate: 0,
      maxDate:jQuery('#date_timepicker_end').val()?jQuery('#date_timepicker_end').val():false,
      scrollMonth: false
     })
    },
    timepicker:false, 
    scrollInput: false
   });
   jQuery('#date_timepicker_end').datetimepicker({
    format:'Y/m/d',
    onShow:function( ct ){
     this.setOptions({
      minDate:jQuery('#date_timepicker_start').val()?jQuery('#date_timepicker_start').val():false,
      scrollMonth: false
     })
    },
    timepicker:false,
    scrollInput: false
   });
  });
</script>

<p>

  <%= form_tag({controller: :events, action: @action}, method: @method, :multipart => true) do %>
  <div class="ui form">
    <% if @action == :create %>
    <div class="field"><label>Dog to Share</label>
      <div class="ui buttons">
        <% @form_filler.all_dogs.each do |dog| %>
          <div class="ui button">
            <% @form_filler.dogs.include?(dog) ? bool = true : bool = false %>
            <%= check_box_tag "dogs[#{dog}]", 1, bool, :class => "check" %>
            <%= label(:dogs, dog, dog) %>
          </div>
        <% end %>
      </div>
    </div>
    <% end %>

    <div class="field">
      <label>Start</label>
      <%= text_field :date_timepicker, :start, :readonly => true, :value => @form_filler.start_date_string %>
    </div>

  <br />
    <div class="field">
      <label>End</label>
      <%= text_field :date_timepicker, :end, :readonly => true, :value => @form_filler.end_date_string %>
    </div>

  <br />

  <div class="field"><label>Time of day</label>
    <div class="ui buttons">
    <% @form_filler.times.each do |time| %> 
        <div class="ui button">
        <% @form_filler.values[:time_of_day].include?(time) ? bool = true : bool = false %>
        <%= check_box_tag "times[#{time}]", 1, bool, :class => "check" %>
        <%= label(:times, time, time) %>
        </div>
    <% end %>
    </div>
  </div>

  <br />

  <div class="field"><label>Where</label>
    <% @form_filler.places.each do |place| %>
      <%= radio_button_tag(:my_location, place , @form_filler.values[:my_location] == place ? checked = true : checked = false) %>
      <%= place %>
      <br />
    <% end %>
  </div>

  <br />

  <div class="field">
    <label>Description</label>
    <%= text_area_tag :description, @form_filler.values[:description] %>
  </div>

  <% end %>

  <div class="field">
    <div class="ui primary button transparent input"><input id='update_event_button' type="submit" value="Schedule" name="update_dog_button" class='btn info'  style="text-align:center"/></div>


    <%= button_to "Cancel", root_path(:notice => ""), :id => "cancel_dog_button", :class => "ui button transparent input", :method => :get %>
    </div>
  </div>
</p>

app/views/events/edit.html.erb
<% if flash[:notice] %> 
  <div class="ui warning message"><i class="warning icon"></i>
    <% flash[:notice].each do |msg| %>
      <%= msg[1][0] %>
      <br>
    <% end %>
  </div>
<% end %>

<h2>Edit <%= @dog.name %>'s Event</h2>

<%= button_to "Delete Event", event_path(@event.id), :id => "delete_event_button", :class => "ui button red transparent input", :method => :delete %>

<%= render 'event_form' %>

app/views/events/index.html.erb
<% if flash[:notice] %>
  <div class="ui warning message"><i class="warning icon"></i>
    <%= flash[:notice] %>
      <br>
  </div>
<% end %>


<style type="text/css">
  #calendar
  {
  width: 900px;
  margin: 0 auto;
  }
</style>

<div id='calendar'></div>

<p> </p>
 <%= link_to "Add Event", new_event_path, :class => "ui primary button" %>
<p></p>

<% if current_user.future_events? %>
  <div id = "dogevents"><h3>Upcoming Events:</h3>
 <div class = "large-12 columns">
  <% for dog in @dogs do %>
    <% if dog.future_events? %>
     
     <div class="row">
          <h3 class = "ui ribbon label"> <%= dog.name %> </h3>

  <% for event in dog.future_events %>
<p></p>
 <div class = "large-6 columns">
  <div class = "ui blue inverted top attached segment" style = "overflow:hidden">

          <% if event.start_date == event.end_date %>
             <%= event.start_date.strftime('%v') %>
          <% else %>
             <%= event.start_date.strftime('%v') %> to <%= event.end_date.strftime('%v') %>
          <% end %>
         </div>
         <div class = "ui bottom attached segment">
          <p>
          <strong>Time:</strong> <%= event.time_of_day.join(", ") %>
          <br />
          <strong>Location:</strong> <%= event.my_location %>
          <br />
          <strong>Description:</strong> <%= event.description %>
          <br />
                  <br />
          <%= link_to "Edit", edit_event_path(event.id) %></p>

        </div>
      </div>

    <%end%>



    <% end %>

   </div>
</br>
  <%end%>

  </div>

</br>
</div>

<% else %>
<div id="dogevents"><h3>No upcoming events</h3></div>

<%end%>

app/views/events/new.html.erb
<% if flash[:notice] %>
  <div class="ui warning message"><i class="warning icon"></i>
    <% flash[:notice].values.each do |msg| %>
      <%= msg[0] %>
      <br>
    <% end %>
  </div>
<% end %>

<h2>Create Event</h2>

<%= render 'event_form' %>