config/routes.rb
Citydogshare::Application.routes.draw do
  ## Route Route ##
  root :to => 'welcome#index'

  ## Session Routes ##
  get 'auth/:provider/callback', to: 'sessions#handle_auth', as: 'auth_success'
  get 'auth/failure', to: 'sessions#handle_failure', as: 'auth_failure'
  delete 'signout', to: 'sessions#destroy', as: 'signout'
  get 'create', to: 'sessions#create', as: 'create_session'
  get 'login', to: 'sessions#login', as: 'login'
  get 'signup', to: 'sessions#signup', as: 'signup'
  
  ## User Routes ##
  resources :users, only: [:show, :edit, :update, :destroy, :index]
  post 'users/:id/edit', to: 'users#edit'

  ## Dog Routes ##
  resources :dogs

  resources :events, :only => [:index, :new, :create, :edit, :update, :show, :destroy]

  resources :mixes, :only => [:index, :show] do
    collection do
      get :autocomplete
    end
  end

  resource :starred_dogs, only: [:create, :destroy]
  resources :users do
    member do
      get 'stars'
    end
  end
  #dog multiple pictures
  resources :pictures

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  get 'dashboard' => 'welcome#dashboard'
end

app/controllers/layouts_controller.rb
class LayoutsController < ApplicationController
end

app/helpers/layouts_helper.rb
module LayoutsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>City Dog Share</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body style="background-color:#f7f7f7">

  <div class="row">

    <div class="large-12 columns">
      <div class="ui raised segment large menu" style="position:fixed; top:0; left:0; width:100%; z-index:100;">
          <a href ="/" class="header item">City Dog Share</a>
          <a class="item" href="/dogs">Find a Dog</a>
        <% if current_user %>
          <a class="item" href="/events/new">Share a Dog</a>
          <div class="right menu">
            <%= link_to "My Calendar", events_path, {:class => "item"}%>
            <% if current_user.dogs.count > 0 %>
              <% if current_user.dogs.count == 1 %>
                <%= link_to "My Dogs", dog_path(current_user.dogs.first), {:class => "item"}%>
              <% else %>
                <div class="ui simple dropdown item">
                  My Dogs
                  <div class="menu">
                    <% current_user.dogs.all.each do |dog| %>
                    <div class="item">
                      <%= link_to dog.name, dog_path(dog.id), {:method => :get} %>
                    </div>
                    <% end %>
                  </div>
                </div>
              <% end %>
            <% else %>
              <%= link_to "My Dogs", new_dog_path(:no_dog => 'true'), {:method => :get, :class => "item"}%>
            <% end %>
            <%= link_to "My Favorites", stars_user_path(current_user), {:class => "item"}%>
            <%= link_to "My Profile", user_path(current_user), {:class => "item"}%>
            <%= link_to "Sign Out", signout_path, {:method => :delete, :class => "item"} %>
          </div>

        <% else %>
          <div class="right menu">
            <div class="item">
              <div class="ui facebook button"><i class="facebook icon"></i> <%= link_to "Sign Up","/auth/facebook/?type=signup", id: 'sign_up' %></div>
            </div>
            <div class="item">
              <div class="ui button"><%= link_to "Log In", "/auth/facebook/?type=login", id: 'log_in' %></div>
            </div>
          </div>

        <% end %>

      </div>
    </div>

    <div class="ui raised segment large-12 columns" style="padding-top:40px">

      <div class="row">
        <div class="large-12 columns">
            <img src="/assets/header.png" width="100%"/>
            <br /><br />
        </div>
      </div>

      <%= yield %>
    </div>

    <div class="ui secondary raised segment large-12 columns">
        <p>&copy; City Dog Share 2015.</p>
      </div>

  </div>

</body>
</html>